// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV9jRiJVulDdCa60m9fdwB5ek7oAeQBZY',
    appId: '1:81435083117:web:16866a0a0c899ed709da64',
    messagingSenderId: '81435083117',
    projectId: 'crypto-11663',
    authDomain: 'crypto-11663.firebaseapp.com',
    storageBucket: 'crypto-11663.firebasestorage.app',
    measurementId: 'G-XM4C2TBMQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmcJI8YU2qXdG4OEAPTF4BHJLAiy2-NGc',
    appId: '1:81435083117:android:f0d262b29a6d7f5309da64',
    messagingSenderId: '81435083117',
    projectId: 'crypto-11663',
    storageBucket: 'crypto-11663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDVQT8GCrLmTbtLRcGLXPaGKQEAHie-CU',
    appId: '1:81435083117:ios:8b801ded65ae29ef09da64',
    messagingSenderId: '81435083117',
    projectId: 'crypto-11663',
    storageBucket: 'crypto-11663.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDVQT8GCrLmTbtLRcGLXPaGKQEAHie-CU',
    appId: '1:81435083117:ios:8b801ded65ae29ef09da64',
    messagingSenderId: '81435083117',
    projectId: 'crypto-11663',
    storageBucket: 'crypto-11663.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV9jRiJVulDdCa60m9fdwB5ek7oAeQBZY',
    appId: '1:81435083117:web:92d53881bae026a809da64',
    messagingSenderId: '81435083117',
    projectId: 'crypto-11663',
    authDomain: 'crypto-11663.firebaseapp.com',
    storageBucket: 'crypto-11663.firebasestorage.app',
    measurementId: 'G-Y70P4PJZSB',
  );
}
