// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_application_1/repositories/crypto_coin/models/crypto_coin.dart';
import 'package:flutter_application_1/repositories/crypto_coin/models/crypto_coin_details.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoCoinAdapter());
    registerAdapter(CryptoCoinDetailAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoCoinAdapter());
    registerAdapter(CryptoCoinDetailAdapter());
  }
}
